#! /bin/sh
# /etc/ha.d/resource.d/mon-cluster-nfs
# $Id: mon-cluster-nfs,v 1.2 2005/11/06 13:15:07 doros Exp $

PATH=/bin:/usr/bin:/sbin:/usr/sbin

case "$1" in
  start)
    echo -n "Enabling cluster-nfs"
    
cat <<EOF | moncmd -l mon -a
PASS=mon

enable watch cluster-nfs
EOF

    echo "."
    ;;
  stop)
    echo -n "Disabling cluster-nfs"
    
cat <<EOF | moncmd -l mon -a
PASS=mon

disable watch cluster-nfs
EOF

    echo "."
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0
