#!/bin/bash
# $Id: lab,v 1.3 2005/10/18 13:55:52 doros Exp $

SCRIPTNAME=`echo $0 | awk -vFS='/' '{print $NF}'`

waitfinish()
{
    SEMAPHORE=$1.booting
    touch $SEMAPHORE
    while [ -f $SEMAPHORE ]; do
        sleep 2
    done
    sleep 2
}

notifyfinish()
{
    rm $1.booting
}



startvm()
{
    X="-q --exec=/hosthome${PWD#$HOME}/${SCRIPTNAME}"
    export NETKIT_VM_TYPE=sarge

    ########################################### topology
    #
    #

    echo "Making backing store ..."
    rm -f /tmp/r1
    dd if=/dev/zero of=/tmp/r1 bs=1M seek=50 count=1 2>/dev/null
    rm -f /tmp/r2
    dd if=/dev/zero of=/tmp/r2 bs=1M seek=50 count=1 2>/dev/null
    rm -f /tmp/r3
    dd if=/dev/zero of=/tmp/spare bs=1M seek=50 count=1 2>/dev/null
    echo "Done."
    vstart vHost \
      --append="ubd1=/tmp/r1" \
      --append="ubd2=/tmp/r2" \
      --append="ubd3=/tmp/spare" --mem=128 $X
    waitfinish vHost

    #
    #
    ########################################### end topology
    echo ""
    echo " *** all machines started *** "
}

crashvm()
{
    ########################################### crash
    #
    #
    vcrash vHost
    #
    #
    ########################################### end crash
}


help_exit()
{
        echo "usage: $0 {start|crash}"
        echo "  Run this script from your home or from a subdir"
        echo "  lab start"
        echo "     starts all virtual machines for the lab "
        echo "     press enter after each virtual machines has booted"
        echo "  lab crash"
        echo "     makes all virtual machines to crash and delete .disk files"
        exit 1
}


if [ "$1" = "start" ]; then
     startvm

elif [ "$1" = "crash" ]; then
     crashvm
     rm -f *.disk   *.booting
elif [ "$1" = "clean" ]; then
     rm -f *.disk   *.booting
elif [ ! -z $1 ]; then
     help_exit

elif [ -z $1 ]; then

    if [ `id -u` != "0"  ]; then
        help_exit
    fi


    #
    # this is executed in the virtual machine by vlab_guest when initializing
    # and it is NEVER executed by in the host environment
    #
    SCRIPTFILE=`cat /proc/cmdline | awk -v FS== -v RS=' ' '{if($1=="exec") print $2}' `
    SCRIPTDIR=${SCRIPTFILE%/${SCRIPTNAME}}
    cd $SCRIPTDIR


    case "$HOSTNAME" in

    ################################################### machine configurations
    #
    #

    vHost)
        echo 'export d='$SCRIPTDIR >> /etc/profile
        echo 'export SCRIPTDIR='$SCRIPTDIR >> /etc/profile
        # make XFS filesystem
        mkfs.xfs -q /dev/ubd/1
        mkfs.xfs -q /dev/ubd/2
        mkfs.xfs -q /dev/ubd/3
        # make a raid5
        # create tree md devices
        mknod /dev/md0 b 9 0
        mknod /dev/md1 b 9 1
        mknod /dev/md2 b 9 2

        notifyfinish vHost
        ;;

    #
    #
    ################################################# end machine configurations


    *)
        echo internal error: $HOSTNAME
        exit 1
    esac
fi
