#!/bin/sh
# $Id: lab,v 1.8 2005/10/19 12:47:04 doros Exp $

SCRIPTNAME=`echo $0 | awk -vFS='/' '{print $NF}'`

waitfinish()
{
    SEMAPHORE=$1.booting
    touch $SEMAPHORE
    while [ -f $SEMAPHORE ]; do
        sleep 2
    done
    sleep 5
}

notifyfinish()
{
    rm $1.booting
}



startvm()
{
    X="-q --exec=/hosthome${PWD#$HOME}/${SCRIPTNAME}"
    export NETKIT_VM_TYPE=sarge

    ########################################### topology
    #
    #
    vstart lts --append="eth0=tuntap,tap0"  --mem=128 $X
    waitfinish lts
    #
    #
    ########################################### end topology
    echo ""
    echo " *** all machines started ***"
}

crashvm()
{
    ########################################### crash
    #
    #
    vcrash lts
    #
    #
    ########################################### end crash
}


help_exit()
{
    echo "usage: $0 {start|crash}"
    echo "  Run this script from your home or from a subdir"
    echo "  lab start"
    echo "     starts all virtual machines for the lab "
    echo "     press enter after each virtual machines has booted"
    echo "  lab crash"
    echo "     makes all virtual machines to crash and delete .disk files"
    exit 1
}


if [ "$1" = "start" ]; then
     if [ `grep tap0 /proc/net/dev|wc -l` = 0 ] ; then
       echo "missing tap0 device"
       exit 1
     fi

     # enable X remote display
     xhost +192.168.77.2

     startvm

elif [ "$1" = "crash" ]; then
     crashvm
     rm -f *.disk   *.booting
elif [ ! -z $1 ]; then
     help_exit

elif [ -z $1 ]; then

    if [ `id -u` != "0"  ]; then
        help_exit
    fi


    #
    # this is executed in the virtual machine by vlab_guest when initializing
    # and it is NEVER executed by in the host environment
    #
    SCRIPTFILE=`cat /proc/cmdline | awk -v FS== -v RS=' ' '{if($1=="exec") print $2}' `
    SCRIPTDIR=${SCRIPTFILE%/${SCRIPTNAME}}
    cd $SCRIPTDIR


    case "$HOSTNAME" in

    ################################################### machine configurations
    #
    #
    lts)
        # IP address and route
        ifconfig eth0 192.168.77.1 \
          netmask 255.255.255.0 broadcast 192.168.77.255 up
        #route add default gw 192.168.77.1
        # IP rules
        mv /etc/hosts.allow /etc/hosts.allow.org
        cp $SCRIPTDIR/hosts.allow /etc/hosts.allow
        mv /etc/hosts /etc/hosts.org
        # dhcp
        mv /etc/dhcp3/dhcpd.conf /etc/dhcp3/dhcpd.conf.org
        cp $SCRIPTDIR/dhcpd.conf /etc/dhcp3/dhcpd.conf
        /etc/init.d/dhcp3-server start
        # nfs
        mv /etc/exports /etc/exports.org
        cp $SCRIPTDIR/exports /etc/exports
        /etc/init.d/portmap start
        /etc/init.d/nfs-common start
        /etc/init.d/nfs-user-server start
        # config/startup xinetd
        mv /etc/xinetd.conf /etc/xinetd.conf.org
        cp $SCRIPTDIR/xinetd.conf /etc/xinetd.conf
        /etc/init.d/xinetd start
        # file DNS
        cp $SCRIPTDIR/hosts /etc/hosts
        # LTSP config
        mv /opt/ltsp/i386/etc/lts.conf /opt/ltsp/i386/etc/lts.conf.org
        cp $SCRIPTDIR/lts.conf /opt/ltsp/i386/etc/lts.conf
         # startup xtail
        #export DISPLAY=192.168.77.1:0.0
        #/usr/X11R6/bin/xterm -g 120x15-0+0 -T /var/log/syslog@lts \
        #  -e tail -f /var/log/syslog &


        notifyfinish lts
        ;;

    #
    #
    ################################################ end machine configurations


    *)
        echo internal error: $HOSTNAME
        exit 1
    esac
fi
