#!/bin/sh
# $Id: lab,v 1.13 2006/09/15 12:27:35 doros Exp $

SCRIPTNAME=`echo $0 | awk -vFS='/' '{print $NF}'`

waitfinish()
{
    SEMAPHORE=$1.booting
    touch $SEMAPHORE
    while [ -f $SEMAPHORE ]; do
        sleep 2
    done
    sleep 2
}

notifyfinish()
{
    rm $1.booting
}

# PDC setting
pdc() {
        # IP address
        ifconfig eth0 192.168.50.101
        route add default gw 192.168.50.1
        # setup resolv.conf
        cp $SCRIPTDIR/dns/resolv.conf /etc/resolv.conf
        > /etc/hosts
        # samba PDC
        mv /etc/samba/smb.conf /etc/samba/smb.conf.org
        cp $SCRIPTDIR/smb-Core.conf /etc/samba/smb.conf
        touch /etc/samba/smbusers
        # LDAP
        mv /etc/ldap/ldap.conf /etc/ldap/ldap.conf.org
        cp $SCRIPTDIR/ldap-SAMBA.conf /etc/ldap/ldap.conf
        # nss
        mv /etc/nsswitch.conf /etc/nsswitch.conf.org
        cp $SCRIPTDIR/nsswitch-SAMBA.conf /etc/nsswitch.conf
        mv /etc/libnss-ldap.conf /etc/libnss-ldap.conf.org
        cp $SCRIPTDIR/libnss-ldap-SAMBA.conf /etc/libnss-ldap.conf
        # Configure smbldap-tools
        cp $SCRIPTDIR/smbldap.conf /etc/smbldap-tools/smbldap.conf
        chmod 644 /etc/smbldap-tools/smbldap.conf
        cp $SCRIPTDIR/smbldap_bind.conf /etc/smbldap-tools/smbldap_bind.conf
        chmod 600 /etc/smbldap-tools/smbldap_bind.conf
        # cleanup
        rm -f /var/cache/samba/printing/*tdb \
              /var/cache/samba/*tdb \
              /var/lib/samba/*tdb \
              /var/run/samba/*tdb
        rm -f /var/cache/samba/*dat \
              /var/lib/samba/*dat
        rm -f /var/log/samba/* 
        # set credentials
        smbpasswd -w samba
        # set SID
        net setlocalsid 'S-1-5-21-3840722988-1065274203-713729200'
        # startup samba services
        /etc/init.d/samba start
        # get SID
        net getlocalsid
        # start populate
        /usr/sbin/smbldap-populate -u 2000 -g 1500
        # startup samba services
        /etc/init.d/samba restart
        sleep 2
        # setup admin password
        (sleep 4; echo "not24get"; sleep 4; echo "not24get" ) | \
           smbldap-passwd Administrator
        # join to netkitwg domain
        net rpc join -S CORE -U Administrator%not24get
        # setup home perms
        chmod u=rwx,go=rx /home
        chown root:root /home
        # make share directory
        mkdir -p /home/netlogon/scripts
        cp $SCRIPTDIR/logon.bat /home/netlogon/scripts
        chmod -R 0775 /home/netlogon
        chown -R root:Domain\ Admins /home/netlogon
        mkdir /home/profiles
        chmod 1757 /home/profiles
        # hacking
        mkdir /home/Administrator
        chmod go= /home/Administrator
        > /home/Administrator/file-inCore
        chown administrator:Domain\ Admins /home/Administrator/file-inCore
        # Add Junior Administrator (junior staff needs ability to add machines)
        (sleep 4; echo "secret"; sleep 4; echo "secret" ) |
          smbldap-useradd -a -g 512 -c "Join Administrator" \
            -B 1 -m -P jadmin
        > /home/jadmin/file-inCore
        chown jadmin:Domain\ Admins /home/jadmin/file-inCore
        # grant the members of DA to add client machines to the domain
        net rpc rights grant 'Netkitwg\jadmin' SeMachineAccountPrivilege \
          -S CORE -U Administrator%not24get
        # create a test group/user
        smbldap-groupadd -a gtest
        (sleep 4; echo "secret"; sleep 4; echo "secret" ) |
          smbldap-useradd -a -G gtest -c "Test user" -B 1 -m -P utest
        > /home/utest/file-inCore
        chown utest:Domain\ Users /home/utest/file-inCore
        # create file in [temp] share
        mkdir /tmp/temp
        chmod a+rwx /tmp/temp
        > /tmp/temp/file-inCore
        chmod a=r,go= /tmp/temp/file-inCore
}

# Domain Member setting
# $1 may be missing or "nofault"
dual() {
        # IP address
        if [ "$1" = "nofault" ] ; then
          ifconfig eth0 192.168.50.102
          route add default gw 192.168.50.1
        else
          ifconfig eth0:0 192.168.50.102
        fi
        # setup resolv.conf
        cp $SCRIPTDIR/dns/resolv.conf /etc/resolv.conf
        > /etc/hosts
        # samba Home
        cp $SCRIPTDIR/smb-Home.conf /etc/samba/smbHome.conf
        # LDAP
        mv /etc/ldap/ldap.conf /etc/ldap/ldap.conf.org
        cp $SCRIPTDIR/ldap-SAMBA.conf /etc/ldap/ldap.conf
        # nss
        mv /etc/nsswitch.conf /etc/nsswitch.conf.org
        cp $SCRIPTDIR/nsswitch-SAMBA.conf /etc/nsswitch.conf
        #cp $SCRIPTDIR/nsswitch-HOME.conf /etc/nsswitch.conf
        mv /etc/libnss-ldap.conf /etc/libnss-ldap.conf.org
        cp $SCRIPTDIR/libnss-ldap-SAMBA.conf /etc/libnss-ldap.conf
        # samba init.d startup file
        cp $SCRIPTDIR/sambaHome /etc/init.d/sambaHome
        cp $SCRIPTDIR/winbindHome /etc/init.d/winbindHome
        # samba dir
        mkdir /var/lib/sambaHome
        mkdir -p /var/share/sambaHome
        mkdir /var/run/sambaHome
        mkdir /var/log/sambaHome
        mkdir /var/cache/sambaHome
        mkdir /usr/share/sambaHome
        cp /usr/share/samba/*.dat /usr/share/sambaHome
        # specific binary in /usr/sbin
        cp $SCRIPTDIR/bin/nmbd /usr/sbin/nmbdHome
        cp $SCRIPTDIR/bin/smbd /usr/sbin/smbdHome
        cp $SCRIPTDIR/bin/winbindd /usr/sbin/winbinddHome
        # specific binary in /usr/bin
        cp $SCRIPTDIR/bin/smbpasswd /usr/bin/smbpasswdHome
        cp $SCRIPTDIR/bin/net /usr/bin/netHome
        cp $SCRIPTDIR/bin/pdbedit /usr/bin/pdbeditHome
        cp $SCRIPTDIR/bin/wbinfo /usr/bin/wbinfoHome
        # setup home perms
        chmod u=rwx,go=rx /home
        chown root:root /home
        # directory for share: homes, netlogon, profiles, profdata
        groupadd admin
        mkdir /mnt/homes
        chmod u=rwx,go=rx /mnt/homes
        chown root:root /mnt/homes
        mkdir /mnt/netlogon
        chmod 0775 /mnt/netlogon
        chown root:admin /mnt/netlogon
        mkdir /mnt/profiles
        chmod 1757 /mnt/profiles
        mkdir /mnt/profdata
        chmod 755 /mnt/profdata
        # cleanup and set passwd
        rm -f /var/cache/sambaHome/printing/*tdb \
              /var/cache/sambaHome/*tdb \
              /var/lib/sambaHome/*tdb \
              /var/run/sambaHome/*tdb
        rm -f /var/cache/sambaHome/*dat \
              /var/lib/sambaHome/*dat
        smbpasswdHome -c /etc/samba/smbHome.conf -w samba
        # set SID
        netHome -s /etc/samba/smbHome.conf setlocalsid \
          'S-1-5-21-2566635133-2380124492-2608689044'
        # join to NetkitWG domain
        netHome -s /etc/samba/smbHome.conf rpc join -S CORE \
          -U Administrator%not24get
        # hacking
        mkdir /mnt/homes/Administrator
        chmod go= /mnt/homes/Administrator
        > /mnt/homes/Administrator/file-inHome
        chown administrator:Domain\ Admins /mnt/homes/Administrator/file-inHome
        # create user homes
        mkdir /mnt/homes/utest
        chown utest:Domain\ Users /mnt/homes/utest
        chmod 700 /mnt/homes/utest
        > /mnt/homes/utest/file-inHome
        chown utest:Domain\ Users /mnt/homes/utest/file-inHome
        # create user profile directory
        mkdir /mnt/homes/jadmin
        chown jadmin:Domain\ Admins /mnt/homes/jadmin
        chmod 700 /mnt/homes/jadmin
        > /mnt/homes/jadmin/file-inHome
        chown jadmin:Domain\ Admins /mnt/homes/jadmin/file-inHome
        # create user profile directory
        mkdir /mnt/profiles/utest
        chown utest:Domain\ Users /mnt/profiles/utest
        chmod 700 /mnt/profiles/utest
        # create "DefaultUser" profile
        (cd /mnt/profiles; tar zxf $SCRIPTDIR/DefaultUser.tgz)
        # make profdata data profile
        cp $SCRIPTDIR/mk.sh /root
        chmod u+x /root/mk.sh
        /root/mk.sh /mnt/profdata utest
        # startup samba services
        /etc/init.d/sambaHome start
        #  set credetential for winbind
        wbinfoHome --set-auth-user Netkitwg+Administrator%not24get
        #
        /etc/init.d/winbindHome restart
}

# $1 may be missing or "nofault"
startvm()
{
    X="-q --exec=/hosthome${PWD#$HOME}/${SCRIPTNAME}"
    export NETKIT_VM_TYPE=sarge

    ########################################### topology
    #
    #

    f=~/.Xdefaults-`hostname`
    if [ -f $f ] ; then
      mv $f $f.save
    fi

    echo "*xterm*geometry: 80x15+0+34">$f
    vstart ldap --eth0=A  --append="eth1=tuntap,tap0" --mem=64 $X
    waitfinish ldap

    if [ "$1" = "nofault" ] ; then
      echo "*xterm*geometry: 80x24+0+265">$f
      vstart sambaCore --eth0=A --mem=64 $X
      waitfinish sambaCore

      echo "*xterm*geometry: 80x24+50-75">$f
      vstart sambaHome --eth0=A  --mem=64 $X
      waitfinish sambaHome
    else
      echo "*xterm*geometry: 80x24+0+265">$f
      vstart dualSamba --eth0=A --mem=128 $X
      waitfinish dualSamba
    fi

    if [ -f $f.save ] ; then
      mv $f.save $f
    else
      rm -f $f
    fi

    #
    #
    ########################################### end topology
    echo ""
    echo " *** all machines started *** "
}

# $1 may be missing or "nofault"
crashvm()
{
    ########################################### crash
    #
    #
    vcrash ldap
    if [ "$1" = "nofault" ] ; then
      vcrash sambaCore
      vcrash sambaHome
    else
      vcrash dualSamba
    fi
    #
    #
    ########################################### end crash
}


help_exit()
{
        echo "usage: $0 {start|crash}"
        echo "  Run this script from your home or from a subdir"
        echo "  lab start"
        echo "     starts all virtual machines for the lab "
        echo "     press enter after each virtual machines has booted"
        echo "  lab crash"
        echo "     makes all virtual machines to crash and delete .disk files"
        exit 1
}


if [ "$1" = "start" ]; then
     if [ `grep tap0 /proc/net/dev|wc -l` = 0 ] ; then
       echo "missing tap0 device"
       exit 1
     fi
     startvm $2

elif [ "$1" = "crash" ]; then
     crashvm $2
     rm -f *.disk   *.booting
elif [ "$1" = "clean" ]; then
     rm -f *.disk   *.booting
elif [ ! -z $1 ]; then
     help_exit

elif [ -z $1 ]; then

    if [ `id -u` != "0"  ]; then
        help_exit
    fi


    #
    # this is executed in the virtual machine by vlab_guest when initializing
    # and it is NEVER executed by in the host environment
    #
    SCRIPTFILE=`cat /proc/cmdline | awk -v FS== -v RS=' ' '{if($1=="exec") print $2}' `
    SCRIPTDIR=${SCRIPTFILE%/${SCRIPTNAME}}
    cd $SCRIPTDIR


    case "$HOSTNAME" in

    ################################################### machine configurations
    #
    #

    ldap)
        # configure IP address
        ifconfig eth0 192.168.50.1 up
        # configure tap IP address
        ifconfig eth1 192.168.77.2 up
        route add default gw 192.168.77.1
        # setup resolv.conf
        cp $SCRIPTDIR/dns/resolv.conf /etc/resolv.conf
        > /etc/hosts
        # configure and start bind
        cp $SCRIPTDIR/dns/db.istituto /etc/bind/db.istituto
        cp $SCRIPTDIR/dns/db.root /etc/bind/db.root
        cp $SCRIPTDIR/dns/db.192.168.50 /etc/bind
        cp $SCRIPTDIR/dns/named.conf /etc/bind/named.conf
        /etc/init.d/bind9 start
        # LDAP
        gzip -dc $SCRIPTDIR/samba.schema.gz > /etc/ldap/schema/samba.schema
        mv /etc/ldap/ldap.conf /etc/ldap/ldap.conf.org
        cp $SCRIPTDIR/ldap-SAMBA.conf /etc/ldap/ldap.conf
        # initialize LDAP database
        mv /etc/ldap/slapd.conf /etc/ldap/slapd.conf.org
        cp $SCRIPTDIR/boot-slapd.conf /etc/ldap/slapd.conf
        rm -f /var/lib/ldap/*
        /etc/init.d/slapd start; sleep 2
        ldapadd -x -H ldap://127.0.0.1 -D"cn=admin,dc=istituto,dc=it" -w not24get -f $SCRIPTDIR/boot-base.ldif
        /etc/init.d/slapd stop
        # restart LDAP with definitive setting
        cp $SCRIPTDIR/slapd.access /etc/ldap/slapd.access
        cp $SCRIPTDIR/slapd.conf-master /etc/ldap/slapd.conf
        # copy root password
        #cp $SCRIPTDIR/ldap.secret /etc/ldap.secret
        #chmod 0400 /etc/ldap.secret
        # start slapd
        /etc/init.d/slapd start
        # nss
        mv /etc/nsswitch.conf /etc/nsswitch.conf.org
        cp $SCRIPTDIR/nsswitch-SAMBA.conf /etc/nsswitch.conf
        mv /etc/libnss-ldap.conf /etc/libnss-ldap.conf.org
        cp $SCRIPTDIR/libnss-ldap-SAMBA.conf /etc/libnss-ldap.conf

        notifyfinish ldap
        ;;

    sambaCore)
        pdc

        notifyfinish sambaCore
        ;;

    dualSamba)
        pdc
        dual

        notifyfinish dualSamba
        ;;

    sambaHome)

        # cleanup
        rm -f /var/cache/samba/printing/*tdb \
              /var/cache/samba/*tdb \
              /var/lib/samba/*tdb \
              /var/run/samba/*tdb
        rm -f /var/cache/samba/*dat \
              /var/lib/samba/*dat
        rm -f /var/log/samba/* 
        #
        dual "nofault"

        notifyfinish sambaHome
        ;;

    #
    #
    ################################################# end machine configurations


    *)
        echo internal error: $HOSTNAME
        exit 1
    esac
fi
