#!/bin/sh
# $Id: sambaHome,v 1.2 2005/12/11 22:23:58 doros Exp $
# Start/stops the Samba daemons (nmbd, winbind and smbd).
#
#

# Defaults
RUN_MODE="daemons"
DAEMON=/usr/sbin/winbinddHome
CONF=/etc/samba/smbHome.conf

# Reads config file (will override defaults above)
[ -r /etc/default/samba ] && . /etc/default/samba

NMBDPID=/var/run/sambaHome/nmbd.pid
SMBDPID=/var/run/sambaHome/smbd.pid

# clear conflicting settings from the environment
unset TMPDIR

# See if the daemons are there
test -x /usr/sbin/nmbdHome -a -x /usr/sbin/smbdHome || exit 0

case "$1" in
	start)
		echo -n "Starting Samba daemons:"

		echo -n " nmbdHome"
		start-stop-daemon --start --quiet --exec /usr/sbin/nmbdHome -- -D -s $CONF

		echo -n " winbinddHome"
		start-stop-daemon --start --quiet --exec $DAEMON -- -s $CONF

		if [ "$RUN_MODE" != "inetd" ]; then
			echo -n " smbdHome"
			start-stop-daemon --start --quiet --exec /usr/sbin/smbdHome -- -D -s $CONF
		fi

		echo "."
		;;
	stop)
		echo -n "Stopping Samba daemons: "

		start-stop-daemon --stop --quiet --pidfile $NMBDPID

		# Wait a little and remove stale PID file
		sleep 1
		if [ -f $NMBDPID ] && ! ps h `cat $NMBDPID` > /dev/null
		then
			# Stale PID file (nmbd was succesfully stopped),
			# remove it (should be removed by nmbd itself IMHO.)
			rm -f $NMBDPID
		fi
		echo -n "nmbdHome"

		if [ "$RUN_MODE" != "inetd" ]; then

            start-stop-daemon --stop --quiet --oknodo --exec $DAEMON -- -s $CONF
			echo -n " winbinddHome"

			start-stop-daemon --stop --quiet --pidfile $SMBDPID
			# Wait a little and remove stale PID file
			sleep 1
			if [ -f $SMBDPID ] && ! ps h `cat $SMBDPID` > /dev/null
			then
				# Stale PID file (nmbd was succesfully stopped),
				# remove it (should be removed by smbd itself IMHO.)
				rm -f $SMBDPID
			fi
			echo -n " smbdHome"
		fi

		echo "."

		;;
	reload)
		echo -n "Reloading /usr/lib/smbHome.conf (smbd only)"
		start-stop-daemon --stop --signal HUP --pidfile $SMBDPID

		echo "."
		;;
	restart|force-reload)
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo "Usage: /etc/init.d/sambaHome {start|stop|reload|restart|force-reload}"
		exit 1
		;;
esac

exit 0
