#!/bin/sh
# $Id: winbindHome,v 1.1 2005/12/11 22:23:38 doros Exp $
# Start/stops the winbindd daemon.
#
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin

#DAEMON=/usr/sbin/winbindd
DAEMON=/usr/sbin/winbinddHome
CONF=/etc/samba/smbHome.conf

# clear conflicting settings from the environment
unset TMPDIR

# See if the daemon is there
test -x $DAEMON || exit 0

case "$1" in
	start)
		echo -n "Starting the Winbind daemon: winbinddHome"

		start-stop-daemon --start --quiet --exec $DAEMON -- -s $CONF

		echo "."
		;;
	stop)
		echo -n "Stopping the Winbind daemon: winbinddHome"

		start-stop-daemon --stop --quiet --oknodo --exec $DAEMON -- -s $CONF

		echo "."
		;;
	restart|force-reload)
		echo -n "Restarting the Winbind daemon: winbinddHome"

		start-stop-daemon --stop --quiet --oknodo --exec $DAEMON -- -s $CONF
		sleep 2
		start-stop-daemon --start --quiet --exec $DAEMON -- -s $CONF

		echo "."
		;;
	*)
		echo "Usage: /etc/init.d/winbindHome {start|stop|restart|force-reload}"
		exit 1
		;;
esac

exit 0

