#!/bin/sh
# $Id: lab,v 1.8 2006/06/30 22:26:19 doros Exp $

SCRIPTNAME=`echo $0 | awk -vFS='/' '{print $NF}'`

waitfinish()
{
    SEMAPHORE=$1.booting
    touch $SEMAPHORE
    while [ -f $SEMAPHORE ]; do
        sleep 2
    done
    sleep 5
}

notifyfinish()
{
    rm $1.booting
}



startvm()
{
    X="-q --exec=/hosthome${PWD#$HOME}/${SCRIPTNAME}"
    export NETKIT_VM_TYPE=sarge

    ########################################### topology
    #
    #

    vstart server --append="eth0=tuntap,tap0" --eth1=A  --mem=128 $X
    waitfinish server

    vstart client --eth0=A  --mem=64 $X
    waitfinish client

    #
    #
    ########################################### end topology
    echo ""
    echo " *** all machines started ***"
}

crashvm()
{
    ########################################### crash
    #
    #
    vcrash server
    vcrash client
    #
    #
    ########################################### end crash
}


help_exit()
{
        echo "usage: $0 {start|crash}"
        echo "  Run this script from your home or from a subdir"
        echo "  lab start"
        echo "     starts all virtual machines for the lab "
        echo "     press enter after each virtual machines has booted"
        echo "  lab crash"
        echo "     makes all virtual machines to crash and delete .disk files"
        exit 1
}


if [ "$1" = "start" ]; then
     if [ `grep tap0 /proc/net/dev|wc -l` = 0 ] ; then
       echo "missing tap0 device"
       exit 1
     fi
     startvm

elif [ "$1" = "crash" ]; then
     crashvm
     rm -f *.disk   *.booting
elif [ ! -z $1 ]; then
     help_exit

elif [ -z $1 ]; then

    if [ `id -u` != "0"  ]; then
        help_exit
    fi


    #
    # this is executed in the virtual machine by vlab_guest when initializing
	# and it is NEVER executed by in the host environment
	#
    SCRIPTFILE=`cat /proc/cmdline | awk -v FS== -v RS=' ' '{if($1=="exec") print $2}' `
    SCRIPTDIR=${SCRIPTFILE%/${SCRIPTNAME}}
    cd $SCRIPTDIR


    case "$HOSTNAME" in

    ################################################### machine configurations
    #
    #
    server)
        # config IP for tap device
        ifconfig eth0 192.168.77.2
        route add default gw 192.168.77.1
        # config IP for private network
        ifconfig eth1 192.168.10.1 \
          netmask 255.255.255.248 \
          broadcast 192.168.10.8 up
        cp $SCRIPTDIR/nino-cron /etc/cron.d/nino
        rm -rf /etc/cron.d/mrtg /etc/cron.d/sendmail \
               /etc/cron.d/dhcp-dns /etc/cron.d/imp
        cp $SCRIPTDIR/hosts /etc/hosts
        cp $SCRIPTDIR/trapd.sh /var/www/nino/mod_perl/trapd.sh
        cp $SCRIPTDIR/eventaction.sh /var/www/nino/mod_perl/eventaction.sh
        # Start services (syslog, cron, http, mysql)
        /etc/init.d/cron start
        mv /etc/apache/httpd.conf /etc/apache/httpd.conf.org
        cp $SCRIPTDIR/httpd.conf /etc/apache/httpd.conf
        /etc/init.d/apache start
        /etc/init.d/mysql start
        /var/www/nino/mod_perl/trapd.sh >> /var/log/nino-trapd.log 2>&1 &
        /var/www/nino/mod_perl/eventaction.sh >> /var/log/nino-eventaction.log 2>&1 &
        # fix
        mv /usr/share/perl/5.6.1/NINOSNMP.pm  /usr/share/perl/5.8.4/
        mv /usr/share/perl/5.6.1/BER.pm /usr/share/perl/5.8.4/
        mv /usr/share/perl/5.6.1/SNMP_util.pm  /usr/share/perl/5.8.4/
        #mv /usr/share/perl/5.6.1/Net/SNMP.pm  /usr/share/perl/5.8.4/ ??

        notifyfinish server
        ;;

    client)
        # config IP for private network
        ifconfig eth0 192.168.10.2 \
          netmask 255.255.255.248 \
          broadcast 192.168.10.8 up
        route add default gw 192.168.10.1
        cp $SCRIPTDIR/hosts /etc/hosts
        # Start services (syslog, snmpd)
        cp $SCRIPTDIR/snmpd.conf /etc/snmp/snmpd.conf
        /etc/init.d/snmpd start

        notifyfinish client
        ;;


    #
    #
    ################################################# end machine configurations


    *)
        echo internal error: $HOSTNAME
        exit 1
    esac
fi
