#!/bin/sh
# $Id: lab,v 1.20 2005/10/19 12:43:47 doros Exp $

SCRIPTNAME=`echo $0 | awk -vFS='/' '{print $NF}'`

waitfinish()
{
    SEMAPHORE=$1.booting
    touch $SEMAPHORE
    while [ -f $SEMAPHORE ]; do
        sleep 2
    done
    sleep 2
}

notifyfinish()
{
    rm $1.booting
}



startvm()
{
    X="-q --exec=/hosthome${PWD#$HOME}/${SCRIPTNAME}"
    export NETKIT_VM_TYPE=sarge

    ########################################### topology
    #
    #

    f=~/.Xdefaults-`hostname`
    if [ -f $f ] ; then
      mv $f $f.save
    fi

    echo "*xterm*geometry: 80x24+2+44">$f
    vstart ldap --eth0=A  --mem=64 $X
    waitfinish ldap

    echo "*xterm*geometry: 80x24+2-32">$f
    vstart SRV --append="eth0=tuntap,tap0" --eth1=A  --mem=64 $X
    waitfinish SRV

    echo "*xterm*geometry: 80x15-31-32">$f
    vstart CLNT --eth0=A  --mem=64 $X
    waitfinish CLNT

    if [ -f $f.save ] ; then
      mv $f.save $f
    else
      rm -f $f
    fi

    #
    #
    ########################################### end topology
    echo ""
    echo " *** all machines started ***"
}


crashvm()
{
    ########################################### crash
    #
    #
    vcrash ldap
    vcrash SRV
    vcrash CLNT
    #
    #
    ########################################### end crash
}


help_exit()
{
        echo "usage: $0 {start|crash}"
        echo "  Run this script from your home or from a subdir"
        echo "  lab start"
        echo "     starts all virtual machines for the lab "
        echo "     press enter after each virtual machines has booted"
        echo "  lab crash"
        echo "     makes all virtual machines to crash and delete .disk files"
        exit 1
}


if [ "$1" = "start" ]; then
     if [ `grep tap0 /proc/net/dev|wc -l` = 0 ] ; then
       echo "missing tap0 device"
       exit 1
     fi
     startvm

elif [ "$1" = "crash" ]; then
     crashvm
     rm -f *.disk   *.booting
elif [ ! -z $1 ]; then
     help_exit

elif [ -z $1 ]; then

    if [ `id -u` != "0"  ]; then
        help_exit
    fi


    #
    # this is executed in the virtual machine by vlab_guest when initializing
    # and it is NEVER executed by in the host environment
    #
    SCRIPTFILE=`cat /proc/cmdline | awk -v FS== -v RS=' ' '{if($1=="exec") print $2}' `
    SCRIPTDIR=${SCRIPTFILE%/${SCRIPTNAME}}
    cd $SCRIPTDIR


    case "$HOSTNAME" in

    ################################################### machine configurations
    #
    #
    ldap)
        # configure IP address
        ifconfig eth0 192.168.50.1 up
        route add default gw 192.168.50.10
        # setup resolv.conf
        cp $SCRIPTDIR/dns/resolv.conf /etc/resolv.conf
        > /etc/hosts
        # configure and start bind
        cp $SCRIPTDIR/dns/db.istituto /etc/bind/db.istituto
        cp $SCRIPTDIR/dns/db.root /etc/bind/db.root
        cp $SCRIPTDIR/dns/db.192.168.50 /etc/bind
        cp $SCRIPTDIR/dns/named.conf /etc/bind/named.conf
        /etc/init.d/bind9 start
        # LDAP
        gzip -dc $SCRIPTDIR/samba.schema.gz > /etc/ldap/schema/samba.schema
        mv /etc/ldap/ldap.conf /etc/ldap/ldap.conf.org
        cp $SCRIPTDIR/ldap-SAMBA.conf /etc/ldap/ldap.conf
        # initialize LDAP database
        mv /etc/ldap/slapd.conf /etc/ldap/slapd.conf.org
        cp $SCRIPTDIR/boot-slapd.conf /etc/ldap/slapd.conf
        rm -f /var/lib/ldap/*
        /etc/init.d/slapd start; sleep 2
        ldapadd -x -H ldap://127.0.0.1 -D"cn=admin,dc=istituto,dc=it" -w not24get -f $SCRIPTDIR/boot-base.ldif
        /etc/init.d/slapd stop
        # restart LDAP with definitive setting
        cp $SCRIPTDIR/slapd.access /etc/ldap/slapd.access
        cp $SCRIPTDIR/slapd.conf-master /etc/ldap/slapd.conf
        # copy root password
        #cp $SCRIPTDIR/ldap.secret /etc/ldap.secret
        #chmod 0400 /etc/ldap.secret
        # start slapd
        /etc/init.d/slapd start
        # nss
        mv /etc/nsswitch.conf /etc/nsswitch.conf.org
        cp $SCRIPTDIR/nsswitch-SAMBA.conf /etc/nsswitch.conf
        mv /etc/libnss-ldap.conf /etc/libnss-ldap.conf.org
        cp $SCRIPTDIR/libnss-ldap-SAMBA.conf /etc/libnss-ldap.conf

        notifyfinish ldap
        ;;

    SRV)
        # config IP for tap device
        ifconfig eth0 192.168.77.2
        # config IP for private network
        ifconfig eth1 192.168.50.10 up
        # configure tap0 as default gateway
        route add default gw 192.168.77.1
        # setup resolv.conf
        cp $SCRIPTDIR/dns/resolv.conf /etc/resolv.conf
        > /etc/hosts
        # configure samba server side
        mv /etc/samba/smb.conf /etc/samba/smb.conf.org
        cp $SCRIPTDIR/smb.conf /etc/samba/smb.conf
        touch /etc/samba/smbusers
        # config and start xinetd (for SWAT)
        cp $SCRIPTDIR/xinetd.conf /etc/xinetd.conf
        /etc/init.d/xinetd start
        # LDAP
        mv /etc/ldap/ldap.conf /etc/ldap/ldap.conf.org
        cp $SCRIPTDIR/ldap-SAMBA.conf /etc/ldap/ldap.conf
        # nss
        mv /etc/nsswitch.conf /etc/nsswitch.conf.org
        cp $SCRIPTDIR/nsswitch-SAMBA.conf /etc/nsswitch.conf
        mv /etc/libnss-ldap.conf /etc/libnss-ldap.conf.org
        cp $SCRIPTDIR/libnss-ldap-SAMBA.conf /etc/libnss-ldap.conf
        # Configure smbldap-tools
        cp $SCRIPTDIR/smbldap.conf /etc/smbldap-tools/smbldap.conf
        chmod 644 /etc/smbldap-tools/smbldap.conf
        cp $SCRIPTDIR/smbldap_bind.conf /etc/smbldap-tools/smbldap_bind.conf
        chmod 600 /etc/smbldap-tools/smbldap_bind.conf
        # make samba directory
        mkdir /home/netlogon
        mkdir /home/profiles
        mkdir /home/printers
        mkdir /home/public
        chmod a+rwx /home/public
        # set passwd
        rm /var/lib/samba/*.tdb
        smbpasswd -w samba
        # set SID
        net setlocalsid 'S-1-5-21-3840722988-1065274203-713729200'
        # start samba
        /etc/init.d/samba start
        net getlocalsid
        # start populate
        /usr/sbin/smbldap-populate
        # setup admin password
        (sleep 2; echo "not24get"; sleep 2; echo "not24get" ) | \
           smbldap-passwd Administrator
        # join to netkitwg domain
        net rpc join netkitwg -U Administrator%not24get

        notifyfinish SRV
        ;;

    CLNT)
        # config IP for private network
        ifconfig eth0 192.168.50.11 up
        route add default gw 192.168.50.10
        # setup resolv.conf
        cp $SCRIPTDIR/dns/resolv.conf /etc/resolv.conf
        > /etc/hosts
        # Configure samba client side
        mv /etc/samba/smb.conf /etc/samba/smb.conf.org
        cp $SCRIPTDIR/smb-c.conf /etc/samba/smb.conf
        # nss
        mv /etc/nsswitch.conf /etc/nsswitch.conf.org
        cp $SCRIPTDIR/nsswitch-SAMBA.conf /etc/nsswitch.conf
        mv /etc/libnss-ldap.conf /etc/libnss-ldap.conf.org
        cp $SCRIPTDIR/libnss-ldap-SAMBA.conf /etc/libnss-ldap.conf
        # set passwd
        rm /var/lib/samba/*.tdb
        smbpasswd -w samba
        # get SID
        net rpc getsid netkitwg
        # config/startup autofs
        mv /etc/auto.master /etc/auto.master.org
        cp $SCRIPTDIR/auto.master /etc/auto.master
        mv /etc/auto.smb /etc/auto.smb.org
        cp $SCRIPTDIR/auto.smb /etc/auto.smb
        /etc/init.d/autofs start
        # fix samba bug for automount
        ln -s /sbin/mount.smbfs /bin/mount.smbfs
        # make a mount point
        mkdir /mnt/smb
        # join to netkitwg domain
        net rpc join netkitwg -U Administrator%not24get

        notifyfinish CLNT
        ;;


    #
    #
    ############################################### end machine configurations


    *)
        echo internal error: $HOSTNAME
        exit 1
    esac
fi
