#!/bin/sh
# $Id: lab,v 1.6 2005/10/19 12:45:44 doros Exp $

SCRIPTNAME=`echo $0 | awk -vFS='/' '{print $NF}'`

waitfinish()
{
    SEMAPHORE=$1.booting
    touch $SEMAPHORE
    while [ -f $SEMAPHORE ]; do
        sleep 2
    done
    sleep 2
}

notifyfinish()
{
    rm $1.booting
}



startvm()
{
    X="-q --exec=/hosthome${PWD#$HOME}/${SCRIPTNAME}"
    export NETKIT_VM_TYPE=sarge

    ########################################### topology
    #
    #

    vstart vHost --append="eth0=tuntap,tap0" --mem=64 $X
    waitfinish vHost

    #
    #
    ########################################### end topology
    echo ""
    echo " *** all machines started *** "
}

crashvm()
{
    ########################################### crash
    #
    #
    vcrash vHost
    #
    #
    ########################################### end crash
}


help_exit()
{
        echo "usage: $0 {start|crash}"
        echo "  Run this script from your home or from a subdir"
        echo "  lab start"
        echo "     starts all virtual machines for the lab "
        echo "     press enter after each virtual machines has booted"
        echo "  lab crash"
        echo "     makes all virtual machines to crash and delete .disk files"
        exit 1
}


if [ "$1" = "start" ]; then
     if [ `grep tap0 /proc/net/dev|wc -l` = 0 ] ; then
       echo "missing tap0 device"
       exit 1
     fi

     # enable X remote display
     xhost +192.168.77.2

     startvm

elif [ "$1" = "crash" ]; then
     crashvm
     rm -f *.disk   *.booting
elif [ "$1" = "clean" ]; then
     rm -f *.disk   *.booting
elif [ ! -z $1 ]; then
     help_exit

elif [ -z $1 ]; then

    if [ `id -u` != "0"  ]; then
        help_exit
    fi


    #
    # this is executed in the virtual machine by vlab_guest when initializing
    # and it is NEVER executed by in the host environment
    #
    SCRIPTFILE=`cat /proc/cmdline | awk -v FS== -v RS=' ' '{if($1=="exec") print $2}' `
    SCRIPTDIR=${SCRIPTFILE%/${SCRIPTNAME}}
    cd $SCRIPTDIR


    case "$HOSTNAME" in

    ################################################### machine configurations
    #
    #

    vHost)
        echo 'export d='$SCRIPTDIR >> /etc/profile
        echo 'export SCRIPTDIR='$SCRIPTDIR >> /etc/profile
        # IP address
        ifconfig eth0 192.168.77.2 up
        route add default gw 192.168.77.1
        # setup ENV
        mv /etc/security/pam_env.conf /etc/security/pam_env.conf.org
        cp $SCRIPTDIR/pam_env.conf /etc/security/pam_env.conf
        # enable/config/startup ssh
        rm -f /etc/ssh/sshd_not_to_be_run
        mv /etc/ssh/sshd_config /etc/ssh/sshd_config.org
        cp $SCRIPTDIR/sshd_config /etc/ssh/sshd_config
        /etc/init.d/ssh start
        # ssh & PAM
        cp $SCRIPTDIR/sshusers-allowed /etc/sshusers-allowed
        # pam
        cp $SCRIPTDIR/other /etc/pam.d/other
        # startup xtail
        export DISPLAY=192.168.77.1:0.0
        /usr/X11R6/bin/xterm -g 120x15-0+0 -T /var/log/messages@vHost \
          -e tail -f /var/log/messages &
        /usr/X11R6/bin/xterm -g 120x15-0+254 -T /var/log/auth.log@vHost \
          -e tail -f /var/log/auth.log &
        # setup guest password
        (sleep 1; echo "not24get"; sleep 1; echo "not24get") | passwd guest
        # setup toni account
        useradd -m toni
        (sleep 1; echo "not24get"; sleep 1; echo "not24get") | passwd toni
        # setup motd
        cp $SCRIPTDIR/motd /etc/motd
        # add wheel group
        groupadd wheel
        # add guest to wheel group
        gpasswd -a guest wheel
        cp $SCRIPTDIR/pam_calc.c /root

        notifyfinish vHost
        ;;


    #
    #
    ################################################# end machine configurations


    *)
        echo internal error: $HOSTNAME
        exit 1
    esac
fi
