-- $Id: query3.sql,v 1.1 2005/01/21 09:12:01 doros Exp $

use fgt;

select N_PAGAMENTO, PENALITA.N_GIOCATORE, IMPORTO, COGNOME, INIZIALI
from PENALITA, GIOCATORI
where PENALITA.N_GIOCATORE = GIOCATORI.N_GIOCATORE;

