#!/bin/bash
# $Id: lab,v 1.6 2006/01/19 16:52:06 doros Exp $

SCRIPTNAME=`echo $0 | awk -vFS='/' '{print $NF}'`

waitfinish()
{
    SEMAPHORE=$1.booting
    touch $SEMAPHORE
    while [ -f $SEMAPHORE ]; do
        sleep 2
    done
    sleep 2
}

notifyfinish()
{
    rm $1.booting
}



startvm()
{
    X="-q --exec=/hosthome${PWD#$HOME}/${SCRIPTNAME}"
    export NETKIT_VM_TYPE=sarge

    ########################################### topology
    #
    #

    f=~/.Xdefaults-`hostname`
    if [ -f $f ] ; then
      mv $f $f.save
    fi

    echo "*xterm*geometry: 80x5+258+16">$f
    vstart dns-root --eth0=A --append="eth1=tuntap,tap0" --mem=16 $X
    waitfinish dns-root

    echo "*xterm*geometry: 80x5+11+122">$f
    vstart dns-org --eth0=A --mem=16 $X
    waitfinish dns-org

    echo "*xterm*geometry: 80x5-14+122">$f
    vstart dns-net --eth0=A --mem=16  $X
    waitfinish dns-net

    echo "*xterm*geometry: 80x8+0+222">$f
    vstart dns-lug --eth0=A --mem=34 $X
    waitfinish dns-lug

    echo "*xterm*geometry: 80x8-0+222">$f
    vstart dns-nano --eth0=A --mem=34 $X
    waitfinish dns-nano

    echo "*xterm*geometry: 80x24+0-48">$f
    vstart pc1 --eth0=A --mem=16 $X
    waitfinish pc1

    echo "*xterm*geometry: 80x24-2-48">$f
    vstart pc2 --eth0=A --mem=16 $X
    waitfinish pc2

    if [ -f $f.save ] ; then
      mv $f.save $f
    else
      rm -f $f
    fi


    #
    #
    ########################################### end topology
    echo ""
    echo " *** all machines started ***"
}

crashvm()
{
    ########################################### crash
    #
    #
    vcrash dns-root
    vcrash dns-org
    vcrash dns-net
    vcrash dns-nano
    vcrash dns-lug
    vcrash pc1
    vcrash pc2
    #
    #
    ########################################### end crash
}


help_exit()
{
        echo "usage: $0 {start|crash}"
        echo "  Run this script from your home or from a subdir"
        echo "  lab start"
        echo "     starts all virtual machines for the lab "
        echo "     press enter after each virtual machines has booted"
        echo "  lab crash"
        echo "     makes all virtual machines to crash and delete .disk files"
        exit 1
}


if [ "$1" = "start" ]; then
     if [ `grep tap0 /proc/net/dev|wc -l` = 0 ] ; then
       echo "missing tap0 device"
       exit 1
     fi

     startvm

elif [ "$1" = "crash" ]; then
     crashvm
     rm -f *.disk   *.booting
elif [ "$1" = "clean" ]; then
     rm -f *.disk   *.booting
elif [ ! -z $1 ]; then
     help_exit

elif [ -z $1 ]; then

    if [ `id -u` != "0"  ]; then
        help_exit
    fi


    #
    # this is executed in the virtual machine by vlab_guest when initializing
    # and it is NEVER executed by in the host environment
    #
    SCRIPTFILE=`cat /proc/cmdline | awk -v FS== -v RS=' ' '{if($1=="exec") print $2}' `
    SCRIPTDIR=${SCRIPTFILE%/${SCRIPTNAME}}
    cd $SCRIPTDIR


    case "$HOSTNAME" in

    ################################################### machine configurations
    #
    #
    dns-root)
        ifconfig eth0 192.168.0.5 up
        ifconfig eth1 192.168.77.2 up
        route add default gw 192.168.77.1
        # copying the db of root DNS
        cp $SCRIPTDIR/db.root-virtual /etc/bind/db.root
        cp $SCRIPTDIR/db.192.168.0 /etc/bind
        # copying the confiyguration of root DNS
        cp $SCRIPTDIR/named.conf-rootdns /etc/bind/named.conf
        # restarting bind server 
        /etc/init.d/bind9 start

        notifyfinish dns-root 
        ;;

    dns-org)
        ifconfig eth0 192.168.0.1 up
        route add default gw 192.168.0.5
        # copying the db of lugroma3.org DNS
        cp $SCRIPTDIR/db.root /etc/bind/
        cp $SCRIPTDIR/db.org /etc/bind/
        # copying the configuration of root DNS
        cp $SCRIPTDIR/named.conf-orgdns /etc/bind/named.conf
        # restarting bind server 
        /etc/init.d/bind9 start


        notifyfinish dns-org
        ;;

    dns-net)
        ifconfig eth0 192.168.0.2 up
        route add default gw 192.168.0.5
        # copying the db of lugroma3.org DNS
        cp $SCRIPTDIR/db.root /etc/bind/
        cp $SCRIPTDIR/db.net /etc/bind/
        # copying the configuration of root DNS
        cp $SCRIPTDIR/named.conf-netdns /etc/bind/named.conf
        # restarting bind server 
        /etc/init.d/bind9 start


        notifyfinish dns-net
        ;;

    dns-lug)
        ifconfig eth0 192.168.0.11 up 
        route add default gw 192.168.0.5
        # copying the db of lugroma3.org DNS
        cp $SCRIPTDIR/db.root /etc/bind/
        cp $SCRIPTDIR/db.org.lugroma3 /etc/bind/
        # copying the configuration of root DNS
        cp $SCRIPTDIR/named.conf-lugroma3dns /etc/bind/named.conf
        # restarting bind server 
        /etc/init.d/bind9 start
        # config and start xinetd
        cp $SCRIPTDIR/xinetd.conf /etc/xinetd.conf
        /etc/init.d/xinetd start
        # disable for study purpose tls pop/imap 
        cp $SCRIPTDIR/c-client.cf /etc/c-client.cf
        # configuring the resolver  
        cp $SCRIPTDIR/resolv.conf-dns-lug /etc/resolv.conf
        # config/start Postfix
        cp $SCRIPTDIR/main.cf-dns-lug /etc/postfix/main.cf
        /etc/init.d/postfix start
        # configure mutt
        cp $SCRIPTDIR/.muttrc /root/.muttrc
        # add user
        (sleep 4; echo "not24get"; sleep 4; echo "not24get") | \
           adduser --gecos 'Caio' caio
        (sleep 4; echo "not24get"; sleep 4; echo "not24get") | \
           adduser --gecos 'Bill Porta' bill


        notifyfinish dns-lug
        ;;

    dns-nano)
        ifconfig eth0 192.168.0.22 up 
        route add default gw 192.168.0.5
        # copying the db of nanoinside.net DNS
        cp $SCRIPTDIR/db.root /etc/bind/
        cp $SCRIPTDIR/db.net.nanoinside /etc/bind/
        # copying the configuration of root DNS
        cp $SCRIPTDIR/named.conf-nanoinsidedns /etc/bind/named.conf
        # restarting bind server 
        /etc/init.d/bind9 start
        # config and start xinetd
        cp $SCRIPTDIR/xinetd.conf /etc/xinetd.conf
        /etc/init.d/xinetd start
        # disable for study purpose tls pop/imap 
        cp $SCRIPTDIR/c-client.cf /etc/c-client.cf
        # configuring the resolver  
        cp $SCRIPTDIR/resolv.conf-dns-nano /etc/resolv.conf
        # config/start Postfix
        cp $SCRIPTDIR/main.cf-dns-nano /etc/postfix/main.cf
        /etc/init.d/postfix start
        # configure mutt
        cp $SCRIPTDIR/.muttrc /root/.muttrc
        # add user
        (sleep 4; echo "not24get"; sleep 4; echo "not24get") | \
           adduser --gecos 'Tizio' tizio

        notifyfinish dns-nano
        ;;

    pc1)
        ifconfig eth0 192.168.0.111 up 
        route add default gw 192.168.0.5
        # configuring the resolver  
        cp $SCRIPTDIR/resolv.conf-pc1-org /etc/resolv.conf
        # configure mutt
        cp $SCRIPTDIR/.muttrc-pc1 /root/.muttrc
        # config/start Postfix
        cp $SCRIPTDIR/main.cf-pc1 /etc/postfix/main.cf
        /etc/init.d/postfix start

        notifyfinish pc1
        ;;
 
    pc2)
        ifconfig eth0 192.168.0.222 up 
        route add default gw 192.168.0.5
        # configuring the resolver  
        cp $SCRIPTDIR/resolv.conf-pc2-net /etc/resolv.conf
        # configure mutt
        cp $SCRIPTDIR/.muttrc-pc2 /root/.muttrc
        # config/start Postfix
        cp $SCRIPTDIR/main.cf-pc2 /etc/postfix/main.cf
        /etc/init.d/postfix start
        
        notifyfinish pc2
        ;;
 
    #
    #
    ############################################### end machine configurations


    *)
        echo internal error: $HOSTNAME
        exit 1
    esac
fi


