#!/bin/sh
# $Id: lab,v 1.18 2006/05/13 06:10:26 doros Exp $

SCRIPTNAME=`echo $0 | awk -vFS='/' '{print $NF}'`

waitfinish()
{
    SEMAPHORE=$1.booting
    touch $SEMAPHORE
    while [ -f $SEMAPHORE ]; do
        sleep 2
    done
    sleep 2
}

notifyfinish()
{
    rm $1.booting
}



startvm()
{
    X="-q --exec=/hosthome${PWD#$HOME}/${SCRIPTNAME}"
    export NETKIT_VM_TYPE=sarge

    ########################################### topology
    #
    #

    f=~/.Xdefaults-`hostname`
    if [ -f $f ] ; then
      mv $f $f.save
    fi

    echo "*xterm*geometry: 80x24+2-32">$f
    vstart server  --eth0=A  --mem=64 $X
    waitfinish server

    echo "*xterm*geometry: 80x24+2+44">$f
    vstart rserver --append="eth0=tuntap,tap0" --eth1=A  --mem=64 $X
    waitfinish rserver

    echo "*xterm*geometry: 80x15-31-32">$f
    vstart client  --eth0=A  --mem=64 $X
    waitfinish client

    if [ -f $f.save ] ; then
      mv $f.save $f
    else
      rm -f $f
    fi

    #
    #
    ########################################### end topology
    echo ""
    echo " *** all machines started ***"
}

crashvm()
{
    ########################################### crash
    #
    #
    vcrash server
    vcrash rserver
    vcrash client
    #
    #
    ########################################### end crash
}


help_exit()
{
        echo "usage: $0 {start|crash}"
        echo "  Run this script from your home or from a subdir"
        echo "  lab start"
        echo "     starts all virtual machines for the lab "
        echo "     press enter after each virtual machines has booted"
        echo "  lab crash"
        echo "     makes all virtual machines to crash and delete .disk files"
        exit 1
}


if [ "$1" = "start" ]; then
     if [ `grep tap0 /proc/net/dev|wc -l` = 0 ] ; then
       echo "missing tap0 device"
       exit 1
     fi
     startvm

elif [ "$1" = "crash" ]; then
     crashvm
     rm -f *.disk   *.booting
elif [ ! -z $1 ]; then
     help_exit

elif [ -z $1 ]; then

    if [ `id -u` != "0"  ]; then
        help_exit
    fi


    #
    # this is executed in the virtual machine by vlab_guest when initializing
    # and it is NEVER executed by in the host environment
    #
    SCRIPTFILE=`cat /proc/cmdline | awk -v FS== -v RS=' ' '{if($1=="exec") print $2}' `
    SCRIPTDIR=${SCRIPTFILE%/${SCRIPTNAME}}
    cd $SCRIPTDIR


    case "$HOSTNAME" in

    ################################################### machine configurations
    #
    #
    server)
        # configure IP address
        ifconfig eth0 192.168.50.1 up
        route add default gw 192.168.50.2
        # configure and start bind
        cp $SCRIPTDIR/dns/db.root /etc/bind/db.root
        cp $SCRIPTDIR/dns/db.istituto /etc/bind/db.istituto
        cp $SCRIPTDIR/dns/db.192.168.50 /etc/bind
        cp $SCRIPTDIR/dns/named.conf /etc/bind/named.conf
        /etc/init.d/bind9 start
        # setup resolv.conf
        cp $SCRIPTDIR/dns/resolv.conf /etc/resolv.conf
        > /etc/hosts
        # LDAP boot
        mv /etc/ldap/slapd.conf /etc/ldap/slapd.conf.org
        cp $SCRIPTDIR/boot-slapd.conf /etc/ldap/slapd.conf
        rm -f /var/lib/ldap/*
        /etc/init.d/slapd start; sleep 2
        ldapadd -x -H ldap://127.0.0.1 -D"cn=admin,dc=istituto,dc=it" -w not24get -f $SCRIPTDIR/ldif/boot-base.ldif
        /etc/init.d/slapd stop
        # LDAP client side
        mv /etc/ldap/ldap.conf /etc/ldap/ldap.conf.org
        cp $SCRIPTDIR/ldap.conf /etc/ldap/ldap.conf
        cp $SCRIPTDIR/ldap.conf-tls /etc/ldap/ldap.conf-tls
        # LDAP server side
        cp $SCRIPTDIR/slapd.conf-master /etc/ldap/slapd.conf
        cp $SCRIPTDIR/slapd.conf-master-tls /etc/ldap/slapd.conf-tls
        cp $SCRIPTDIR/slapd.access /etc/ldap/slapd.access
        cp $SCRIPTDIR/slapd.index /etc/ldap/slapd.index
        # copy server certificates
        cp $SCRIPTDIR/tls/server-cert.pem /etc/ldap/ldapcert.pem
        cp $SCRIPTDIR/tls/server-key.pem /etc/ldap/ldapkey.pem
        chmod 0400 /etc/ldap/ldapkey.pem
        cp $SCRIPTDIR/tls/cacert.pem /etc/ldap/cacert.pem
        # NSS
        mv /etc/nsswitch.conf /etc/nsswitch.conf.org
        cp $SCRIPTDIR/nsswitch.conf /etc/nsswitch.conf.clear
        cp $SCRIPTDIR/nsswitch.conf /etc/nsswitch.conf
        mv /etc/libnss-ldap.conf /etc/libnss-ldap.conf.org
        cp $SCRIPTDIR/libnss-ldap.conf-master /etc/libnss-ldap.conf.clear
        cp $SCRIPTDIR/libnss-ldap.conf-master /etc/libnss-ldap.conf
        cp $SCRIPTDIR/libnss-ldap.conf-tls /etc/libnss-ldap.conf-tls
        # tls startup parms
        cp $SCRIPTDIR/slapd-master /etc/default/slapd-master
        # copy nssuser password
        cp $SCRIPTDIR/ldap.secret /etc/ldap.secret
        chmod 0400 /etc/ldap.secret
        # start slapd
        slapindex
        /etc/init.d/slapd start
        # populate from ldif
        ldapadd -x -H ldap://127.0.0.1 -D"cn=admin,ou=DSA,dc=istituto,dc=it" \
          -w Wserver -f $SCRIPTDIR/ldif/base.ldif
        ldapadd -x -H ldap://127.0.0.1 -D"cn=admin,ou=DSA,dc=istituto,dc=it" \
          -w Wserver -f $SCRIPTDIR/ldif/group.ldif
        ldapadd -x -H ldap://127.0.0.1 -D"cn=admin,ou=DSA,dc=istituto,dc=it" \
          -w Wserver -f $SCRIPTDIR/ldif/hosts.ldif
        ldapadd -x -H ldap://127.0.0.1 -D"cn=admin,ou=DSA,dc=istituto,dc=it" \
          -w Wserver -f $SCRIPTDIR/ldif/passwd.ldif

        notifyfinish server
        ;;

    rserver)
        # configure IP address for tap device
        ifconfig eth0 192.168.77.2 up
        route add default gw 192.168.77.1
        # configure IP address for eth1
        ifconfig eth1 192.168.50.2 up
        # setup resolv.conf
        cp $SCRIPTDIR/dns/resolv.conf /etc/resolv.conf
        > /etc/hosts
        # LDAP boot
        mv /etc/ldap/slapd.conf /etc/ldap/slapd.conf.org
        cp $SCRIPTDIR/boot-slapd.conf /etc/ldap/slapd.conf
        rm -f /var/lib/ldap/*
        /etc/init.d/slapd start; sleep 2
        ldapadd -x -H ldap://127.0.0.1 -D"cn=admin,dc=istituto,dc=it" \
          -w not24get -f $SCRIPTDIR/ldif/boot-base.ldif
        /etc/init.d/slapd stop
        # LDAP client side
        mv /etc/ldap/ldap.conf /etc/ldap/ldap.conf.org
        cp $SCRIPTDIR/ldap.conf /etc/ldap/ldap.conf
        cp $SCRIPTDIR/ldap.conf-tls /etc/ldap/ldap.conf-tls
        # LDAP
        #cp $SCRIPTDIR/ldap.conf /etc/ldap/ldap.conf
        #cp $SCRIPTDIR/ldap.conf-tls /etc/ldap/ldap.conf-tls
        cp $SCRIPTDIR/slapd.access-replica /etc/ldap/slapd.access-replica
        cp $SCRIPTDIR/slapd.conf-replica /etc/ldap/slapd.conf
        cp $SCRIPTDIR/slapd.conf-replica-tls /etc/ldap/slapd.conf-tls
        cp $SCRIPTDIR/slapd.index /etc/ldap/slapd.index
        # copy certificates
        cp $SCRIPTDIR/tls/rserver-cert.pem /etc/ldap/ldapcert.pem
        cp $SCRIPTDIR/tls/rserver-key.pem /etc/ldap/ldapkey.pem
        chmod 0400 /etc/ldap/ldapkey.pem
        cp $SCRIPTDIR/tls/cacert.pem /etc/ldap/cacert.pem
        # tls startup parms
        cp $SCRIPTDIR/slapd-replica /etc/default/slapd-replica
        # NSS
        mv /etc/nsswitch.conf /etc/nsswitch.conf.org
        cp $SCRIPTDIR/nsswitch.conf /etc/nsswitch.conf.clear
        cp $SCRIPTDIR/nsswitch.conf /etc/nsswitch.conf
        mv /etc/libnss-ldap.conf /etc/libnss-ldap.conf.org
        cp $SCRIPTDIR/libnss-ldap.conf /etc/libnss-ldap.conf.clear
        cp $SCRIPTDIR/libnss-ldap.conf /etc/libnss-ldap.conf
        cp $SCRIPTDIR/libnss-ldap.conf-tls /etc/libnss-ldap.conf-tls
        # copy nssuser password
        cp $SCRIPTDIR/ldap.secret /etc/ldap.secret
        chmod 0400 /etc/ldap.secret
        # restart slapd
        slapindex
        /etc/init.d/slapd start

        notifyfinish rserver
        ;;

    client)
        # configure IP address
        ifconfig eth0 192.168.50.3 up
        route add default gw 192.168.50.2
        # LDAP client side
        mv /etc/ldap/ldap.conf /etc/ldap/ldap.conf.org
        cp $SCRIPTDIR/ldap.conf /etc/ldap/ldap.conf
        cp $SCRIPTDIR/ldap.conf-tls /etc/ldap/ldap.conf-tls
        # copy certificates
        cp $SCRIPTDIR/tls/client-cert.pem /etc/ldap/ldapcert.pem
        cp $SCRIPTDIR/tls/client-key.pem /etc/ldap/ldapkey.pem
        chmod 0400 /etc/ldap/ldapkey.pem
        cp $SCRIPTDIR/tls/cacert.pem /etc/ldap/cacert.pem
        # setup resolv.conf
        cp $SCRIPTDIR/dns/resolv.conf /etc/resolv.conf
        > /etc/hosts
        # NSS
        mv /etc/nsswitch.conf /etc/nsswitch.conf.org
        cp $SCRIPTDIR/nsswitch.conf /etc/nsswitch.conf.clear
        cp $SCRIPTDIR/nsswitch.conf /etc/nsswitch.conf
        mv /etc/libnss-ldap.conf /etc/libnss-ldap.conf.org
        cp $SCRIPTDIR/libnss-ldap.conf /etc/libnss-ldap.conf.clear
        cp $SCRIPTDIR/libnss-ldap.conf /etc/libnss-ldap.conf
        cp $SCRIPTDIR/libnss-ldap.conf-tls /etc/libnss-ldap.conf-tls
        # copy nssuser password
        cp $SCRIPTDIR/ldap.secret /etc/ldap.secret
        chmod 0400 /etc/ldap.secret
        # PAM
        cp /etc/pam_ldap.conf /etc/pam_ldap.conf.org
        cp $SCRIPTDIR/pam_ldap.conf /etc/pam_ldap.conf.new
        cp $SCRIPTDIR/pam_ldap.conf-tls /etc/pam_ldap.conf-tls
        cp -R $SCRIPTDIR/pam.d/common-auth /etc/pam.d/common-auth.new
        cp -R $SCRIPTDIR/pam.d/common-account /etc/pam.d/common-account.new
        cp -R $SCRIPTDIR/pam.d/common-session /etc/pam.d/common-session.new
        # Start sshd daemon
        rm -f /etc/ssh/sshd_not_to_be_run
        cp  $SCRIPTDIR/sshd_config /etc/ssh/sshd_config
        /etc/init.d/ssh start
        # create home directory
        mkdir /home/nane
        chown 1003:1005 /home/nane
        mkdir /home/toni
        chown 1004:1005 /home/toni
        # remove guest account user
        sed /guest/d /etc/passwd > a
        mv -f a /etc/passwd
        # remove guest account group
        sed /guest/d /etc/group > a
        mv -f a /etc/group

        notifyfinish client
        ;;

    #
    #
    ################################################### machine configurations


    *)
        echo internal error: $HOSTNAME
        exit 1
    esac
fi
