#!/bin/sh
# $Id: OpenPEC,v 1.2 2005/10/19 12:42:55 doros Exp $

SCRIPTNAME=`echo $0 | awk -vFS='/' '{print $NF}'`

waitfinish()
{
    SEMAPHORE=$1.booting
    touch $SEMAPHORE
    while [ -f $SEMAPHORE ]; do
        sleep 2
    done
    sleep 2
}

notifyfinish()
{
    rm $1.booting
}



startvm()
{
    X="-q --exec=/hosthome${PWD#$HOME}/${SCRIPTNAME}"
    export NETKIT_VM_TYPE=sarge

    ########################################### topology
    #
    #

    vstart OpenPECserver --append="eth0=tuntap,tap0" --mem=128 $X
    waitfinish OpenPECserver

    #
    #
    ########################################### end topology
    echo ""
    echo " *** all machines started ***"
}

crashvm()
{
    ########################################### crash
    #
    #
    vcrash OpenPECserver
    #
    #
    ########################################### end crash
}


help_exit()
{
        echo "usage: $0 {start|crash}"
        echo "  Run this script from your home or from a subdir"
        echo "  lab start"
        echo "     starts all virtual machines for the lab "
        echo "     press enter after each virtual machines has booted"
        echo "  lab crash"
        echo "     makes all virtual machines to crash and delete .disk files"
        exit 1
}


if [ "$1" = "start" ]; then
     if [ `grep tap0 /proc/net/dev|wc -l` = 0 ] ; then
       echo "missing tap0 device"
       exit 1
     fi
     startvm

elif [ "$1" = "crash" ]; then
     crashvm
     rm -f *.disk   *.booting
elif [ ! -z $1 ]; then
     help_exit

elif [ -z $1 ]; then

    if [ `id -u` != "0"  ]; then
        help_exit
    fi


    #
    # this is executed in the virtual machine by vlab_guest when initializing
    # and it is NEVER executed by in the host environment
    #
    SCRIPTFILE=`cat /proc/cmdline | awk -v FS== -v RS=' ' '{if($1=="exec") print $2}' `
    SCRIPTDIR=${SCRIPTFILE%/${SCRIPTNAME}}
    cd $SCRIPTDIR


    case "$HOSTNAME" in

    ################################################### machine configurations
    #
    #
    OpenPECserver)
        # configure IP address
        ifconfig eth0 192.168.77.2
        route add default gw 192.168.77.1
        # LDAP boot
        mv /etc/ldap/slapd.conf /etc/ldap/slapd.conf.org
        cp $SCRIPTDIR/ind_pec.schema  /etc/ldap/schema/ind_pec.schema
        cp $SCRIPTDIR/OpenPEC-boot-slapd.conf /etc/ldap/slapd.conf
        rm -f /var/lib/ldap/*
        slapadd -f /etc/ldap/slapd.conf -l $SCRIPTDIR/ldif/OpenPEC-example.ldif
        cp $SCRIPTDIR/ldif/exp_pec.ldif /root
        /etc/init.d/slapd start

        notifyfinish OpenPECserver
        ;;


    #
    #
    ################################################### machine configurations


    *)
        echo internal error: $HOSTNAME
        exit 1
    esac
fi
