#!/bin/sh
# $Id:$

if [ "none$ENV $KNO" != "none" ]; then

popd $KNO/source

./var/lib/menu-xdg/desktop-directories/menu-xdg/debian-xshells.directory
./var/lib/menu-xdg/desktop-directories/menu-xdg/debian-knoppix.directory
./var/lib/menu-xdg/desktop-directories/menu-xdg/debian-knoppix-utilities.directory
./var/lib/menu-xdg/desktop-directories/menu-xdg/debian-knoppix-services.directory
./var/lib/menu-xdg/desktop-directories/menu-xdg/debian-knoppix-net.directory
./var/lib/menu-xdg/desktop-directories/menu-xdg/debian-knoppix-config.directory
./var/lib/menu-xdg/desktop-directories/menu-xdg/debian-help.directory
./var/lib/menu-xdg/desktop-directories/menu-xdg/debian-apps.directory
./var/lib/menu-xdg/desktop-directories/menu-xdg/debian-apps-viewers.directory
./var/lib/menu-xdg/desktop-directories/menu-xdg/debian-apps-tools.directory
./var/lib/menu-xdg/desktop-directories/menu-xdg/debian-apps-text.directory
./var/lib/menu-xdg/desktop-directories/menu-xdg/debian-apps-system.directory
./var/lib/menu-xdg/desktop-directories/menu-xdg/debian-apps-system-admin.directory
./var/lib/menu-xdg/desktop-directories/menu-xdg/debian-apps-sound.directory
./var/lib/menu-xdg/desktop-directories/menu-xdg/debian-apps-shells.directory
./var/lib/menu-xdg/desktop-directories/menu-xdg/debian-apps-programming.directory
./var/lib/menu-xdg/desktop-directories/menu-xdg/debian-apps-net.directory
./var/lib/menu-xdg/desktop-directories/menu-xdg/debian-apps-math.directory
./var/lib/menu-xdg/desktop-directories/menu-xdg/debian-apps-graphics.directory
./var/lib/menu-xdg/desktop-directories/menu-xdg/debian-apps-editors.directory
./var/lib/menu-xdg/applications/menu-xdg/wireless_lan.desktop
./var/lib/menu-xdg/applications/menu-xdg/wavelan_configuration.desktop
./var/lib/menu-xdg/applications/menu-xdg/swap_file_configuration.desktop
./var/lib/menu-xdg/applications/menu-xdg/start_syslog.desktop
./var/lib/menu-xdg/applications/menu-xdg/start_ssh_server.desktop
./var/lib/menu-xdg/applications/menu-xdg/start_samba_server.desktop
./var/lib/menu-xdg/applications/menu-xdg/start_nx_server.desktop
./var/lib/menu-xdg/applications/menu-xdg/start_knoppix_terminal_server.desktop
./var/lib/menu-xdg/applications/menu-xdg/soundcard_configuration.desktop
./var/lib/menu-xdg/applications/menu-xdg/set_password_for_root.desktop
./var/lib/menu-xdg/applications/menu-xdg/save_knoppix_configuration.desktop
./var/lib/menu-xdg/applications/menu-xdg/samba_network_neighborhood.desktop
./var/lib/menu-xdg/applications/menu-xdg/root_shell.desktop
./var/lib/menu-xdg/applications/menu-xdg/network_card_configuration.desktop
./var/lib/menu-xdg/applications/menu-xdg/nessus_security_scanner.desktop
./var/lib/menu-xdg/applications/menu-xdg/ndiswrapper_configuration.desktop
./var/lib/menu-xdg/applications/menu-xdg/modem_dialer.desktop
./var/lib/menu-xdg/applications/menu-xdg/manage_software_in_knoppix_\(kpackage\).desktop
./var/lib/menu-xdg/applications/menu-xdg/kwrite.desktop
./var/lib/menu-xdg/applications/menu-xdg/kwikdisk.desktop
./var/lib/menu-xdg/applications/menu-xdg/kview.desktop
./var/lib/menu-xdg/applications/menu-xdg/kuickshow.desktop
./var/lib/menu-xdg/applications/menu-xdg/ktnef.desktop
./var/lib/menu-xdg/applications/menu-xdg/ktip.desktop
./var/lib/menu-xdg/applications/menu-xdg/ktimer.desktop
./var/lib/menu-xdg/applications/menu-xdg/ksync.desktop
./var/lib/menu-xdg/applications/menu-xdg/ksnapshot.desktop
./var/lib/menu-xdg/applications/menu-xdg/krfb.desktop
./var/lib/menu-xdg/applications/menu-xdg/krdc.desktop
./var/lib/menu-xdg/applications/menu-xdg/kprinter.desktop
./var/lib/menu-xdg/applications/menu-xdg/kppp_-_logview.desktop
./var/lib/menu-xdg/applications/menu-xdg/kppp.desktop
./var/lib/menu-xdg/applications/menu-xdg/kphone_voip.desktop
./var/lib/menu-xdg/applications/menu-xdg/kpersonalizer.desktop
./var/lib/menu-xdg/applications/menu-xdg/kpdf.desktop
./var/lib/menu-xdg/applications/menu-xdg/kpager.desktop
./var/lib/menu-xdg/applications/menu-xdg/konsole.desktop
./var/lib/menu-xdg/applications/menu-xdg/konqueror.desktop
./var/lib/menu-xdg/applications/menu-xdg/knotes.desktop
./var/lib/menu-xdg/applications/menu-xdg/knoppix_firewall.desktop
./var/lib/menu-xdg/applications/menu-xdg/kmix.desktop
./var/lib/menu-xdg/applications/menu-xdg/kmenuedit.desktop
./var/lib/menu-xdg/applications/menu-xdg/kmail_kab_import_tool.desktop
./var/lib/menu-xdg/applications/menu-xdg/kmail.desktop
./var/lib/menu-xdg/applications/menu-xdg/klipper.desktop
./var/lib/menu-xdg/applications/menu-xdg/kjobviewer.desktop
./var/lib/menu-xdg/applications/menu-xdg/kinfocenter.desktop
./var/lib/menu-xdg/applications/menu-xdg/kiconedit.desktop
./var/lib/menu-xdg/applications/menu-xdg/kicker.desktop
./var/lib/menu-xdg/applications/menu-xdg/khexedit.desktop
./var/lib/menu-xdg/applications/menu-xdg/kghostview.desktop
./var/lib/menu-xdg/applications/menu-xdg/kget.desktop
./var/lib/menu-xdg/applications/menu-xdg/kfloppy.desktop
./var/lib/menu-xdg/applications/menu-xdg/kfind.desktop
./var/lib/menu-xdg/applications/menu-xdg/keditbookmarks.desktop
./var/lib/menu-xdg/applications/menu-xdg/kdiskfree.desktop
./var/lib/menu-xdg/applications/menu-xdg/kdeprintfax.desktop
./var/lib/menu-xdg/applications/menu-xdg/kdepasswd.desktop
./var/lib/menu-xdg/applications/menu-xdg/kdebugdialog.desktop
./var/lib/menu-xdg/applications/menu-xdg/kde_user_manager.desktop
./var/lib/menu-xdg/applications/menu-xdg/kde_sysv-init_editor.desktop
./var/lib/menu-xdg/applications/menu-xdg/kde_system_guard_-_process_table.desktop
./var/lib/menu-xdg/applications/menu-xdg/kde_system_guard.desktop
./var/lib/menu-xdg/applications/menu-xdg/kde_package_manager.desktop
./var/lib/menu-xdg/applications/menu-xdg/kde_help_center.desktop
./var/lib/menu-xdg/applications/menu-xdg/kdcop.desktop
./var/lib/menu-xdg/applications/menu-xdg/kcontrol.desktop
./var/lib/menu-xdg/applications/menu-xdg/kcharselect.desktop
./var/lib/menu-xdg/applications/menu-xdg/kcalc.desktop
./var/lib/menu-xdg/applications/menu-xdg/kate.desktop
./var/lib/menu-xdg/applications/menu-xdg/kappfinder.desktop
./var/lib/menu-xdg/applications/menu-xdg/kandy.desktop
./var/lib/menu-xdg/applications/menu-xdg/kalarm.desktop
./var/lib/menu-xdg/applications/menu-xdg/kaffeine.desktop
./var/lib/menu-xdg/applications/menu-xdg/isdn_connection_\(knoppix\).desktop
./var/lib/menu-xdg/applications/menu-xdg/isdn_connection.desktop
./var/lib/menu-xdg/applications/menu-xdg/harddisk_cd_dvd_dma_acelleration.desktop
./var/lib/menu-xdg/applications/menu-xdg/gprs_umts_connection.desktop
./var/lib/menu-xdg/applications/menu-xdg/fsview.desktop
./var/lib/menu-xdg/applications/menu-xdg/create_a_persistent_knoppix_disk_image.desktop
./var/lib/menu-xdg/applications/menu-xdg/configure_printer\(s\).desktop
./var/lib/menu-xdg/applications/menu-xdg/choose_restart_knoppix_desktop.desktop
./var/lib/menu-xdg/applications/menu-xdg/ark.desktop
./var/lib/menu-xdg/applications/menu-xdg/adsl_pppoe_configuration.desktop
./var/lib/menu-xdg/applications/menu-xdg/_dev_modem_connection_setup_\(serial_usb_irda_bluetooth\).desktop

popd

fi
