# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the browser is running,
 * the changes will be overwritten when the browser exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1156858160);
user_pref("app.update.lastUpdateTime.background-update-timer", 1156858146);
user_pref("browser.cache.disk.capacity", 500);
user_pref("browser.download.defaultFolder", "/home/knoppix");
user_pref("browser.preferences.lastpanel", 4);
user_pref("browser.search.selectedEngine", "Google");
user_pref("browser.startup.homepage", "/cdrom/index.html");
user_pref("extensions.disabledObsolete", true);
user_pref("extensions.lastAppVersion", "1.5.0.6");
user_pref("font.default", "sans-serif");
user_pref("font.name.monospace.x-western", "Bitstream Vera Sans Mono");
user_pref("font.name.sans-serif.x-western", "Bitstream Vera Sans");
user_pref("font.name.serif.x-western", "Bitstream Vera Serif");
user_pref("font.size.fixed.x-western", 14);
user_pref("font.size.variable.x-western", 18);
user_pref("intl.charset.default", "ISO-8859-15");
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1");
user_pref("network.cookie.prefsMigrated", true);
user_pref("security.OCSP.URL", "");
user_pref("security.OCSP.signingCA", "Builtin Object Token:IPS CLASE1 root");
