#!/bin/sh
# $Id: lab,v 1.2 2005/10/19 12:46:11 doros Exp $

SCRIPTNAME=`echo $0 | awk -vFS='/' '{print $NF}'`

waitfinish()
{
    SEMAPHORE=$1.booting
    touch $SEMAPHORE
    while [ -f $SEMAPHORE ]; do
        sleep 2
    done
    sleep 2
}

notifyfinish()
{
    rm $1.booting
}



startvm()
{
    X="-q --exec=/hosthome${PWD#$HOME}/${SCRIPTNAME}"
    export NETKIT_VM_TYPE=sarge

    ########################################### topology
    #
    #

    f=~/.Xdefaults-`hostname`
    if [ -f $f ] ; then
      mv $f $f.save
    fi

    echo "*xterm*geometry: 60x15+10+29">$f
    vstart Cisco2503a  --eth0=A  --eth1=B --eth2=C --mem=32 $X
    waitfinish Cisco2503a

    echo "*xterm*geometry: 60x15+387+28">$f
    vstart Cisco2503b  --eth0=B  --eth1=I --eth2=H --mem=32 $X
    waitfinish Cisco2503b

    echo "*xterm*geometry: 60x15+183+259">$f
    vstart Cisco1600  --eth0=C  --eth1=I --eth2=D --mem=32 $X
    waitfinish Cisco1600

    echo "*xterm*geometry: 60x15-3+260">$f
    vstart Cisco2503c  --eth0=H  --eth1=G --mem=32 $X
    waitfinish Cisco2503c

    echo "*xterm*geometry: 60x15+236-46">$f
    vstart AN2  --append="eth0=tuntap,tap0" --eth1=D  --eth2=E --mem=64 $X
    waitfinish AN2

    echo "*xterm*geometry: 60x15-36-45">$f
    vstart AN1  --eth0=E  --eth1=F --eth2=G --mem=32 $X
    waitfinish AN1

    if [ -f $f.save ] ; then
      mv $f.save $f
    else
      rm -f $f
    fi

    #
    #
    ########################################### end topology
    echo ""
    echo " *** all machines started ***"
}

crashvm()
{
    ########################################### crash
    #
    #
    vcrash Cisco2503a
    vcrash Cisco2503b
    vcrash Cisco1600
    vcrash Cisco2503c
    vcrash AN2
    vcrash AN1
    #
    #
    ########################################### end crash
}


help_exit()
{
        echo "usage: $0 {start|crash}"
        echo "  Run this script from your home or from a subdir"
        echo "  lab start"
        echo "     starts all virtual machines for the lab "
        echo "     press enter after each virtual machines has booted"
        echo "  lab crash"
        echo "     makes all virtual machines to crash and delete .disk files"
        exit 1
}


if [ "$1" = "start" ]; then
     if [ `grep tap0 /proc/net/dev|wc -l` = 0 ] ; then
       echo "missing tap0 device"
       exit 1
     fi
     startvm

elif [ "$1" = "crash" ]; then
     crashvm
     rm -f *.disk   *.booting
elif [ ! -z $1 ]; then
     help_exit

elif [ -z $1 ]; then

    if [ `id -u` != "0"  ]; then
        help_exit
    fi


    #
    # this is executed in the virtual machine by vlab_guest when initializing
    # and it is NEVER executed by in the host environment
    #
    SCRIPTFILE=`cat /proc/cmdline | awk -v FS== -v RS=' ' '{if($1=="exec") print $2}' `
    SCRIPTDIR=${SCRIPTFILE%/${SCRIPTNAME}}
    cd $SCRIPTDIR


    case "$HOSTNAME" in

    ################################################### machine configurations
    #
    #
    Cisco2503a)
        # configure IP address
        ifconfig eth0 192.168.128.1 up
        ifconfig eth1 192.168.1.1 up
        ifconfig eth2 192.168.3.1 up
        #
        cp $SCRIPTDIR/Cisco2503a-zebra.conf /etc/zebra/zebra.conf
        cp $SCRIPTDIR/Cisco2503a-ripd.conf /etc/zebra/ripd.conf
        cp $SCRIPTDIR/daemons /etc/zebra/daemons
        #/etc/init.d/zebra start

        notifyfinish Cisco2503a
        ;;

    Cisco2503b)
        # configure IP address
        ifconfig eth0 192.168.1.2 up
        ifconfig eth1 192.168.2.2 up
        ifconfig eth2 192.168.65.2 up
        #
        cp $SCRIPTDIR/Cisco2503b-zebra.conf /etc/zebra/zebra.conf
        cp $SCRIPTDIR/Cisco2503b-ripd.conf /etc/zebra/ripd.conf
        cp $SCRIPTDIR/daemons /etc/zebra/daemons
        #/etc/init.d/zebra start

        notifyfinish Cisco2503b
        ;;

    Cisco1600)
        # configure IP address
        ifconfig eth0 192.168.3.9 up
        ifconfig eth1 192.168.2.9 up
        ifconfig eth2 192.168.64.9 up
        #
        cp $SCRIPTDIR/Cisco1600-zebra.conf /etc/zebra/zebra.conf
        cp $SCRIPTDIR/Cisco1600-ripd.conf /etc/zebra/ripd.conf
        cp $SCRIPTDIR/daemons /etc/zebra/daemons
        #/etc/init.d/zebra start

        notifyfinish Cisco1600
        ;;

    AN2)
        ifconfig eth0 192.168.77.2 up
        # configure IP address
        ifconfig eth1 192.168.64.4 up
        ifconfig eth2 192.168.67.4 up
        #
        cp $SCRIPTDIR/AN2-zebra.conf /etc/zebra/zebra.conf
        cp $SCRIPTDIR/AN2-ripd.conf /etc/zebra/ripd.conf
        cp $SCRIPTDIR/daemons /etc/zebra/daemons
        #/etc/init.d/zebra start
        cp $SCRIPTDIR/mrlg.cgi /usr/lib/cgi-bin/mrlg.cgi
        /etc/init.d/apache start

        notifyfinish AN2
        ;;

    AN1)
        # configure IP address
        ifconfig eth0 192.168.67.3 up
        ifconfig eth1 192.168.16.3 up
        ifconfig eth2 192.168.66.3 up
        #
        cp $SCRIPTDIR/AN1-zebra.conf /etc/zebra/zebra.conf
        cp $SCRIPTDIR/AN1-ripd.conf /etc/zebra/ripd.conf
        cp $SCRIPTDIR/daemons /etc/zebra/daemons
        #/etc/init.d/zebra start

        notifyfinish AN1
        ;;

    Cisco2503c)
        # configure IP address
        ifconfig eth0 192.168.65.7 up
        ifconfig eth1 192.168.66.7 up
        #
        cp $SCRIPTDIR/Cisco2503c-zebra.conf /etc/zebra/zebra.conf
        cp $SCRIPTDIR/Cisco2503c-ripd.conf /etc/zebra/ripd.conf
        cp $SCRIPTDIR/daemons /etc/zebra/daemons
        #/etc/init.d/zebra start

        notifyfinish Cisco2503c
        ;;


    #
    #
    ################################################### machine configurations


    *)
        echo internal error: $HOSTNAME
        exit 1
    esac
fi
